on:
  workflow_dispatch:
    inputs:
      test_inputs:
        description: 'Test inputs'
        default: 'Test asd'
      test_bool:
        description: boolean options
        type: boolean
        default: True
      test_choice:
        description: Choice test
        type: choice
        options: [dev,test]
      test_number:
        type: number
        default: 1
jobs:

  test-action:
    uses: ./.github/workflow/action@main
    
  test-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$TEST"
          echo "${{ inputs.test_inputs }}"
          echo "${{ inputs.test_bool }}"
          echo "${{ inputs.test_choice }}"
          echo "${{ inputs.test_number }}"          
        env:
          TEST: ${{ inputs.test_inputs }}

      - if: inputs.test_bool
        run: echo "${{ inputs.test_choice }}"

  test-reusable:
      uses: ./.github/workflows/reusable.yml  # Lokalny
      with:
        test-input: ${{ inputs.test_inputs }}
  test-var:
      runs-on: ubuntu-latest
      needs: test-reusable
      steps:
        - run: echo "${{ needs.test-reusable.outputs.test-var }}"
